"use client";
import Link from "next/link";
import { Save } from "lucide-react";
import { useActionState } from "react";
import { Field, inputClass, textAreaClass } from "@/components/form-fields";
import { FormFeedback } from "@/components/form-feedback";
import { expenseCategories } from "@/lib/domain/finance";
import { saveExpense, type ExpenseState } from "./actions";
export function ExpenseForm({ today, jobs, equipment }: { today: string; jobs: { id: number; label: string }[]; equipment: { id: number; name: string }[] }) { const [state, action, pending] = useActionState(saveExpense, {} as ExpenseState); return <form action={action} className="mt-6 space-y-6"><div className="grid gap-5 sm:grid-cols-2">
  <Field errors={state.errors?.expenseDate} label="Date" name="expenseDate"><input className={inputClass} defaultValue={today} id="expenseDate" name="expenseDate" required type="date" /></Field><Field errors={state.errors?.category} label="Category" name="category"><select className={inputClass} id="category" name="category" required><option value="">Select category</option>{expenseCategories.map((item) => <option key={item}>{item}</option>)}</select></Field>
  <Field errors={state.errors?.vendor} label="Vendor" name="vendor"><input className={inputClass} id="vendor" name="vendor" /></Field><Field errors={state.errors?.amount} label="Amount" name="amount"><input className={inputClass} id="amount" min="0" name="amount" required step="0.01" type="number" /></Field>
  <Field errors={state.errors?.paymentMethod} label="Payment method" name="paymentMethod"><input className={inputClass} id="paymentMethod" name="paymentMethod" /></Field><Field errors={state.errors?.jobId} label="Job (optional)" name="jobId"><select className={inputClass} id="jobId" name="jobId"><option value="">No job</option>{jobs.map((job) => <option key={job.id} value={job.id}>{job.label}</option>)}</select></Field>
  <Field errors={state.errors?.equipmentId} label="Equipment (optional)" name="equipmentId"><select className={inputClass} id="equipmentId" name="equipmentId"><option value="">No equipment</option>{equipment.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field errors={state.errors?.description} label="Description" name="description"><input className={inputClass} id="description" name="description" /></Field>
  <div className="sm:col-span-2"><Field errors={state.errors?.notes} label="Notes" name="notes"><textarea className={textAreaClass} id="notes" name="notes" /></Field></div></div><FormFeedback message={state.message} /><div className="flex gap-3 border-t border-line pt-5"><button className="flex h-11 items-center gap-2 rounded-md bg-brand px-4 font-semibold text-on-brand disabled:opacity-60" disabled={pending}><Save size={17} />{pending ? "Saving..." : "Save expense"}</button><Link className="flex h-11 items-center rounded-md border border-line-strong px-4 font-semibold" href="/expenses">Cancel</Link></div></form>; }
