import type { Metadata } from "next";
import Link from "next/link";
import { Plus } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { requireBusinessContext } from "@/lib/auth";
import { formatCurrency, formatDate } from "@/lib/format";
import { listExpenses } from "@/lib/repositories/expense-repository";
import { createClient } from "@/lib/supabase/server";
export const metadata: Metadata = { title: "Expenses" };
export default async function ExpensesPage() { const { business } = await requireBusinessContext(); const expenses = await listExpenses(await createClient(), business.id); const total = expenses.reduce((sum, expense) => sum + expense.amount, 0); return <div className="mx-auto w-full max-w-[1300px] px-4 py-6 sm:px-6 lg:px-8"><PageHeader actions={<Link className="flex h-11 items-center gap-2 rounded-md bg-brand px-4 font-semibold text-on-brand" href="/expenses/new"><Plus size={18} />Add expense</Link>} description={`${expenses.length} records · ${formatCurrency(total)} total`} title="Expenses" /><div className="mt-5 overflow-hidden rounded-lg border border-line bg-surface shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-surface-muted text-xs uppercase text-muted"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Vendor / description</th><th className="px-4 py-3">Linked record</th><th className="px-4 py-3 text-right">Amount</th></tr></thead><tbody className="divide-y divide-line">{expenses.map((expense) => <tr key={expense.id}><td className="px-4 py-4">{formatDate(expense.expense_date)}</td><td className="px-4 py-4 font-semibold">{expense.category}</td><td className="px-4 py-4"><p>{expense.vendor || "No vendor"}</p><p className="text-sm text-muted">{expense.description || "No description"}</p></td><td className="px-4 py-4 text-sm">{expense.jobs ? <Link className="text-brand" href={`/jobs/${expense.jobs.id}`}>{expense.jobs.work_description || `Job #${expense.jobs.id}`}</Link> : expense.equipment?.name || "Not linked"}</td><td className="px-4 py-4 text-right font-semibold">{formatCurrency(expense.amount)}</td></tr>)}{!expenses.length && <tr><td className="px-5 py-14 text-center text-muted" colSpan={5}>No expenses recorded.</td></tr>}</tbody></table></div></div></div>; }
