import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { requireBusinessContext } from "@/lib/auth";
import { calculateFifoPortfolio } from "@/lib/domain/digital-assets";
import { dateInTimeZone } from "@/lib/domain/jobs";
import { formatCurrency, formatDate } from "@/lib/format";
import { listDigitalAssetAccounts, listDigitalAssetReconciliations, listDigitalAssetTransactions } from "@/lib/repositories/business-finance-repository";
import { createClient } from "@/lib/supabase/server";
import { DigitalAssetAccountForm, DigitalAssetImportForm, DigitalAssetReconciliationForm } from "../business-forms";

export const metadata: Metadata = { title: "Digital Assets" };

export default async function DigitalAssetsPage() {
  const context = await requireBusinessContext();
  const client = await createClient();
  const [accounts, records, reconciliations] = await Promise.all([listDigitalAssetAccounts(client, context.business.id), listDigitalAssetTransactions(client, context.business.id), listDigitalAssetReconciliations(client, context.business.id)]);
  const transactions = records.map((row) => ({ id: row.id, occurredAt: row.occurred_at, transactionType: row.transaction_type as "buy", assetSymbol: row.asset_symbol, units: row.units, unitPriceUsd: row.unit_price_usd, grossAmountUsd: row.gross_amount_usd, feeUsd: row.fee_usd, externalId: row.external_id, transferReference: row.transfer_reference, memo: row.memo, fingerprint: row.fingerprint }));
  const portfolio = calculateFifoPortfolio(transactions);
  return <div className="mx-auto w-full max-w-[1400px] px-4 py-6 sm:px-6 lg:px-8"><PageHeader actions={<Link className="flex h-11 items-center gap-2 rounded-md border border-line-strong px-4 font-semibold" href="/finance"><ArrowLeft size={17} />Finance</Link>} description="Track exchange activity, units, FIFO cost basis, fees, transfers, sales, and realized gains without treating assets as revenue." title="Digital Assets" />
    <section className="grid grid-cols-2 gap-3 py-6 sm:grid-cols-4">{[["Accounts", String(accounts.length)], ["Transactions", String(transactions.length)], ["Assets held", String(portfolio.holdings.length)], ["Realized gain/loss", formatCurrency(portfolio.realizedGainLoss)]].map(([label, value]) => <div className="rounded-lg border border-line bg-surface p-4 shadow-sm" key={label}><p className="text-xl font-bold">{value}</p><p className="mt-1 text-xs text-muted">{label}</p></div>)}</section>
    <div className="grid gap-5 lg:grid-cols-[1fr_360px]"><div className="space-y-5"><section className="rounded-lg border border-line bg-surface p-5 shadow-sm"><h2 className="font-bold">FIFO holdings</h2><div className="mt-4 divide-y divide-line">{portfolio.holdings.map((holding) => <div className="flex justify-between py-3" key={holding.assetSymbol}><span className="font-semibold">{holding.assetSymbol} · {holding.units.toFixed(8)} units</span><strong>{formatCurrency(holding.costBasis)}</strong></div>)}{!portfolio.holdings.length && <p className="text-sm text-muted">Import exchange activity to calculate holdings.</p>}</div></section><section className="rounded-lg border border-line bg-surface p-5 shadow-sm"><h2 className="font-bold">Exchange reconciliations</h2><div className="mt-3 divide-y divide-line">{reconciliations.map((row) => <div className="py-3 text-sm" key={row.id}><p className="font-semibold">{row.digital_asset_accounts?.name} · {formatDate(row.as_of_date)}</p><p className="text-muted">{JSON.stringify(row.reported_balances)} · Cash {formatCurrency(row.reported_cash_usd)}</p></div>)}{!reconciliations.length && <p className="text-sm text-muted">No as-of balances saved.</p>}</div></section><section className="overflow-hidden rounded-lg border border-line bg-surface shadow-sm"><h2 className="border-b border-line px-5 py-4 font-bold">Transactions</h2><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-surface-muted text-left text-xs uppercase text-muted"><tr><th className="px-4 py-3">Date</th><th>Type</th><th>Asset</th><th className="text-right">Units</th><th className="px-4 text-right">Gross / fee</th></tr></thead><tbody className="divide-y divide-line">{records.map((row) => <tr key={row.id}><td className="px-4 py-3">{formatDate(row.occurred_at)}</td><td>{row.transaction_type.replaceAll("_", " ")}</td><td className="font-bold">{row.asset_symbol}</td><td className="text-right tabular-nums">{row.units}</td><td className="px-4 text-right">{formatCurrency(row.gross_amount_usd)} / {formatCurrency(row.fee_usd)}</td></tr>)}</tbody></table></div></section></div><div className="space-y-5"><section className="rounded-lg border border-line bg-surface p-5 shadow-sm"><h2 className="mb-4 font-bold">Import exchange CSV</h2><DigitalAssetImportForm accounts={accounts} /></section><section className="rounded-lg border border-line bg-surface p-5 shadow-sm"><h2 className="mb-4 font-bold">Reconcile exchange balance</h2><DigitalAssetReconciliationForm accounts={accounts} defaultDate={dateInTimeZone(context.business.timezone)} /></section><section className="rounded-lg border border-line bg-surface p-5 shadow-sm"><h2 className="mb-4 font-bold">Add exchange or wallet</h2><DigitalAssetAccountForm /></section></div></div>
  </div>;
}
