"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireBusinessContext } from "@/lib/auth";
import { dateInTimeZone } from "@/lib/domain/jobs";
import { createInvoiceRecord, getInvoice, updateInvoiceStatus } from "@/lib/repositories/invoice-repository";
import { createClient } from "@/lib/supabase/server";
import { formValues, invoiceFormSchema } from "@/lib/validation/business-records";
export type InvoiceFormState = { message?: string; errors?: Record<string, string[]> };
export async function saveInvoice(_: InvoiceFormState, formData: FormData): Promise<InvoiceFormState> { const parsed = invoiceFormSchema.safeParse(formValues(formData, ["customerId", "jobId", "amount", "invoiceDate", "dueDate", "paymentTerms", "status", "paidDate", "notes"])); if (!parsed.success) return { errors: parsed.error.flatten().fieldErrors }; if (!parsed.data.customerId || parsed.data.amount === undefined || !parsed.data.invoiceDate) return { message: "Customer, amount, and invoice date are required." }; const { business } = await requireBusinessContext(); try { const id = await createInvoiceRecord(await createClient(), { businessId: business.id, ...parsed.data, customerId: parsed.data.customerId, amount: parsed.data.amount, invoiceDate: parsed.data.invoiceDate }); revalidatePath("/invoices"); revalidatePath("/jobs"); revalidatePath("/dashboard"); redirect(`/invoices/${id}`); } catch (error) { if (error && typeof error === "object" && "digest" in error) throw error; return { message: error instanceof Error ? error.message : "The invoice could not be created." }; } }
export async function markInvoice(invoiceId: number, _: InvoiceFormState, formData: FormData): Promise<InvoiceFormState> { const status = String(formData.get("status") || ""); if (!["draft", "unpaid", "paid", "void"].includes(status)) return { message: "Select a valid invoice status." }; const { business } = await requireBusinessContext(); const client = await createClient(); if (!(await getInvoice(client, business.id, invoiceId))) return { message: "That invoice no longer exists." }; const paidDate = status === "paid" ? dateInTimeZone(business.timezone) : null; await updateInvoiceStatus(client, business.id, invoiceId, status, paidDate); revalidatePath(`/invoices/${invoiceId}`); revalidatePath("/invoices"); revalidatePath("/dashboard"); return { message: "Invoice status updated." }; }
