import type { Metadata } from "next";
import Link from "next/link";
import { BriefcaseBusiness, CalendarDays, CircleDollarSign, Clock3, FileText, Users, Wrench } from "lucide-react";
import { requireBusinessContext } from "@/lib/auth";
import { dashboardRangeOptions, resolveDashboardRange } from "@/lib/domain/dashboard";
import { dateInTimeZone } from "@/lib/domain/jobs";
import { formatCurrency, formatDate, formatTime } from "@/lib/format";
import { quoteDashboardSummary } from "@/lib/repositories/quote-repository";
import { getEntityCounts, getOperationalDashboard } from "@/lib/repositories/reporting-repository";
import { createClient } from "@/lib/supabase/server";

export const metadata: Metadata = { title: "Dashboard" };
function CustomerName({ customer }: { customer: { first_name: string | null; last_name: string | null; company_name: string | null } | null }) { return <>{customer?.company_name || [customer?.first_name, customer?.last_name].filter(Boolean).join(" ") || "Customer"}</>; }
function JobQueue({ title, href, jobs }: { title: string; href: string; jobs: { id: number; work_description: string | null; scheduled_date: string | null; scheduled_start_time: string | null; customers: { first_name: string | null; last_name: string | null; company_name: string | null } | null }[] }) { return <section className="overflow-hidden rounded-lg border border-line bg-surface shadow-sm"><div className="flex items-center justify-between border-b border-line px-4 py-3"><h2 className="font-bold">{title}</h2><Link className="text-sm font-semibold text-brand" href={href}>View all</Link></div>{jobs.length ? <div className="divide-y divide-line">{jobs.slice(0, 5).map((job) => <Link className="block px-4 py-3 hover:bg-page" href={`/jobs/${job.id}`} key={job.id}><p className="truncate font-semibold">{job.work_description || "Job details"}</p><p className="mt-1 text-sm text-muted"><CustomerName customer={job.customers} />{job.scheduled_date ? ` · ${formatDate(job.scheduled_date)}` : ""}{job.scheduled_start_time ? ` · ${formatTime(job.scheduled_start_time)}` : ""}</p></Link>)}</div> : <p className="px-4 py-8 text-center text-sm text-muted">Nothing in this queue.</p>}</section>; }

export default async function DashboardPage({ searchParams }: { searchParams: Promise<{ range?: string; from?: string; to?: string }> }) {
  const { business } = await requireBusinessContext(); const client = await createClient(); const today = dateInTimeZone(business.timezone); const query = await searchParams;
  const dateRange = resolveDashboardRange(today, query.range, query.from, query.to);
  const [dashboard, counts, quotes] = await Promise.all([getOperationalDashboard(client, business.id, today, dateRange), getEntityCounts(client, business.id, dateRange), quoteDashboardSummary(client, business.id, dateRange.start, dateRange.end)]);
  const metrics = [["Revenue", formatCurrency(dashboard.metrics.revenue)], ["Operating expense", formatCurrency(dashboard.metrics.expenses)], ["Asset purchases", formatCurrency(dashboard.metrics.capitalPurchases)], ["Refunds", formatCurrency(dashboard.metrics.refunds)], ["Net cash outflow", formatCurrency(dashboard.metrics.cashOutflow)], ["Outstanding invoices", formatCurrency(dashboard.metrics.outstandingInvoices)], ["Average payment", formatCurrency(dashboard.metrics.averagePaidJob)], ["Bank items to review", String(dashboard.metrics.unreviewedBankTransactions)]];
  const sales = [["Draft", quotes.draftCount, "/quotes?status=draft"], ["Awaiting response", quotes.awaitingResponseCount, "/quotes?view=awaiting_response"], ["Accepted, not converted", quotes.acceptedUnconvertedCount, "/quotes?view=accepted_unconverted"], ["Outstanding value", formatCurrency(quotes.outstandingValue), "/quotes?view=outstanding"], ["Acceptance rate", `${quotes.acceptanceRate}%`, "/quotes"]];
  return <div className="mx-auto w-full max-w-[1440px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><header className="flex flex-wrap items-end justify-between gap-4 border-b border-line pb-5"><div><p className="text-sm font-semibold text-muted">{formatDate(today)}</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Business overview</h1></div><div className="flex gap-2"><Link className="h-10 rounded-md border border-line-strong bg-surface px-3 py-2 font-semibold" href="/imports/jobs">Import jobs</Link><Link className="h-10 rounded-md bg-brand px-3 py-2 font-semibold text-on-brand" href="/quotes/new">New quote</Link></div></header>
    <form className="mt-5 flex flex-wrap items-end gap-3 rounded-lg border border-line bg-surface p-4 shadow-sm" method="get"><label className="grid gap-1 text-sm font-semibold"><span>Date range</span><select className="h-10 rounded-md border border-line-strong bg-surface px-3" defaultValue={dateRange.selected} name="range">{dashboardRangeOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold"><span>From</span><input className="h-10 rounded-md border border-line-strong bg-surface px-3" defaultValue={query.from ?? dateRange.start ?? ""} name="from" type="date" /></label><label className="grid gap-1 text-sm font-semibold"><span>To</span><input className="h-10 rounded-md border border-line-strong bg-surface px-3" defaultValue={query.to ?? dateRange.end ?? ""} name="to" type="date" /></label><button className="h-10 rounded-md bg-brand px-4 font-semibold text-on-brand" type="submit">Apply</button><p className="pb-2 text-sm text-muted">Showing stats for {dateRange.label.toLowerCase()}.</p></form>
    <section className="grid grid-cols-2 gap-3 py-5 sm:grid-cols-4 xl:grid-cols-8" aria-label="Business metrics">{metrics.map(([label, value]) => <Link className="rounded-lg border border-line bg-surface p-4 shadow-sm hover:border-brand-border" href={label === "Bank items to review" ? "/finance?status=unreviewed" : "/reports"} key={label}><p className="text-xl font-bold tabular-nums">{value}</p><p className="mt-1 text-xs text-muted">{label}</p></Link>)}</section>
    <section className="grid gap-5 xl:grid-cols-[1.2fr_0.8fr]"><div><div className="mb-3 flex items-center gap-2"><CalendarDays className="text-brand" size={20} /><h2 className="text-lg font-bold">Today&apos;s work</h2></div><div className="grid gap-4 md:grid-cols-2"><JobQueue href="/jobs?view=today" jobs={dashboard.todayJobs} title="Today's jobs" /><JobQueue href="/jobs?view=upcoming" jobs={dashboard.upcomingJobs} title="Upcoming jobs" /><JobQueue href="/jobs?view=unscheduled" jobs={dashboard.unscheduledJobs} title="Awaiting scheduling" /><JobQueue href="/jobs?status=completed" jobs={dashboard.completedAwaitingInvoice} title="Ready for invoicing" /></div></div>
      <div className="space-y-5"><section className="rounded-lg border border-line bg-surface p-5 shadow-sm"><div className="flex items-center gap-2"><FileText className="text-brand" size={19} /><h2 className="font-bold">Quote pipeline</h2></div><div className="mt-4 grid grid-cols-2 gap-2">{sales.map(([label, value, href]) => <Link className="rounded-md border border-line bg-page px-3 py-3 hover:border-brand-border" href={String(href)} key={label}><p className="font-bold tabular-nums">{value}</p><p className="mt-1 text-xs text-muted">{label}</p></Link>)}</div></section>
      <section className="overflow-hidden rounded-lg border border-line bg-surface shadow-sm"><div className="flex items-center justify-between border-b border-line px-4 py-3"><div className="flex items-center gap-2"><CircleDollarSign className="text-brand" size={18} /><h2 className="font-bold">Unpaid invoices</h2></div><Link className="text-sm font-semibold text-brand" href="/invoices?status=unpaid">View all</Link></div>{dashboard.unpaidInvoices.length ? <div className="divide-y divide-line">{dashboard.unpaidInvoices.slice(0, 5).map((invoice) => <Link className="flex justify-between gap-3 px-4 py-3 hover:bg-page" href={`/invoices/${invoice.id}`} key={invoice.id}><span className="font-semibold">{invoice.invoice_number}</span><span>{formatCurrency(invoice.amount)}</span></Link>)}</div> : <p className="px-4 py-7 text-center text-sm text-muted">No unpaid invoices.</p>}</section>
      <section className="overflow-hidden rounded-lg border border-line bg-surface shadow-sm"><div className="flex items-center justify-between border-b border-line px-4 py-3"><div className="flex items-center gap-2"><Wrench className="text-brand" size={18} /><h2 className="font-bold">Upcoming maintenance</h2></div><Link className="text-sm font-semibold text-brand" href="/equipment">View all</Link></div>{dashboard.upcomingMaintenance.length ? <div className="divide-y divide-line">{dashboard.upcomingMaintenance.map((record) => <Link className="block px-4 py-3 hover:bg-page" href={`/equipment/maintenance/new?equipmentId=${record.equipment_id}`} key={record.id}><p className="font-semibold">{record.equipment?.name || "Equipment"}</p><p className="text-sm text-muted">{record.service_type} · {formatDate(record.next_due_date)}</p></Link>)}</div> : <p className="px-4 py-7 text-center text-sm text-muted">No maintenance due.</p>}</section></div></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-[0.7fr_1.3fr]"><div className="rounded-lg border border-line bg-surface p-5 shadow-sm"><div className="flex items-center gap-2"><Clock3 className="text-brand" size={18} /><h2 className="font-bold">Team productivity</h2></div><dl className="mt-4 grid grid-cols-2 gap-4"><div><dt className="text-xs text-muted">Total jobs</dt><dd className="text-xl font-bold">{dashboard.metrics.totalJobs}</dd></div><div><dt className="text-xs text-muted">Total hours worked</dt><dd className="text-xl font-bold">{dashboard.metrics.totalHoursWorked.toFixed(1)}</dd></div><div><dt className="text-xs text-muted">Total time grinding</dt><dd className="text-xl font-bold">{dashboard.metrics.totalGrindingHours.toFixed(1)} hr</dd></div><div><dt className="text-xs text-muted">Machine hours</dt><dd className="text-xl font-bold">{dashboard.metrics.machineHours.toFixed(1)}</dd></div></dl></div><div className="rounded-lg border border-line bg-surface p-5 shadow-sm"><h2 className="font-bold">Revenue by referral source</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{dashboard.referralRevenue.map(([source, value]) => <div className="flex justify-between gap-4 border-b border-line pb-2 text-sm" key={source}><span>{source}</span><strong>{formatCurrency(value)}</strong></div>)}</div></div></section>
    <section className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><Link className="rounded-lg border border-line bg-surface p-4" href="/customers"><Users size={18} /><strong className="mt-3 block text-xl">{counts.customers}</strong><span className="text-sm text-muted">Active customers</span></Link><Link className="rounded-lg border border-line bg-surface p-4" href="/jobs"><BriefcaseBusiness size={18} /><strong className="mt-3 block text-xl">{counts.jobs}</strong><span className="text-sm text-muted">Active jobs</span></Link><Link className="rounded-lg border border-line bg-surface p-4" href="/quotes"><FileText size={18} /><strong className="mt-3 block text-xl">{counts.quotes}</strong><span className="text-sm text-muted">Open quotes</span></Link><Link className="rounded-lg border border-line bg-surface p-4" href="/invoices?status=unpaid"><CircleDollarSign size={18} /><strong className="mt-3 block text-xl">{counts.invoices}</strong><span className="text-sm text-muted">Unpaid invoices</span></Link></section>
  </div>;
}
