"use client";

import { useActionState, useState } from "react";
import { FormFeedback } from "@/components/form-feedback";
import { Field, inputClass, textAreaClass } from "@/components/form-fields";
import { addCapitalTransaction, addCleanupItem, addDigitalAssetAccount, classifyAllUnclassified, classifyRecord, importDigitalAssetCsv, postHistoricalCleanupItem, reconcileDigitalAssetAccount, updateBusinessIdentity, type BusinessFinanceState } from "./business-actions";

type Option = { id: number; name: string };
const initial = {} as BusinessFinanceState;
const buttonClass = "h-11 rounded-md bg-brand px-4 font-semibold text-on-brand disabled:opacity-60";

export function DigitalAssetAccountForm() {
  const [state, action, pending] = useActionState(addDigitalAssetAccount, initial);
  return <form action={action} className="grid gap-3 sm:grid-cols-2"><Field errors={state.errors?.name} label="Account name" name="name"><input className={inputClass} name="name" required /></Field><Field label="Provider" name="provider"><input className={inputClass} name="provider" /></Field><Field label="Type" name="accountType"><select className={inputClass} defaultValue="exchange" name="accountType"><option value="exchange">Exchange</option><option value="wallet">Wallet</option><option value="custodian">Custodian</option><option value="other">Other</option></select></Field><Field label="External reference" name="externalReference"><input className={inputClass} name="externalReference" /></Field><div className="sm:col-span-2"><FormFeedback message={state.message} tone={state.success ? "success" : "danger"} /></div><button className={buttonClass} disabled={pending}>{pending ? "Adding..." : "Add account"}</button></form>;
}

export function DigitalAssetImportForm({ accounts }: { accounts: Option[] }) {
  const [state, action, pending] = useActionState(importDigitalAssetCsv, initial);
  return <form action={action} className="grid gap-3" encType="multipart/form-data"><Field errors={state.errors?.accountId} label="Exchange or wallet" name="accountId"><select className={inputClass} defaultValue="" name="accountId" required><option disabled value="">Select account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></Field><Field errors={state.errors?.file} label="Exchange CSV" name="file"><input accept=".csv,text/csv" className={inputClass} name="file" required type="file" /></Field><p className="text-xs text-muted">Required columns: Date, Type, Asset, Units. Optional: Price USD, Gross USD, Fee USD, Transaction ID, Transfer Reference, Memo.</p><FormFeedback message={state.message} tone={state.success ? "success" : "danger"} /><button className={buttonClass} disabled={pending || !accounts.length}>{pending ? "Importing..." : "Import idempotently"}</button></form>;
}

export function DigitalAssetReconciliationForm({ accounts, defaultDate }: { accounts: Option[]; defaultDate: string }) {
  const [state, action, pending] = useActionState(reconcileDigitalAssetAccount, initial);
  return <form action={action} className="grid gap-3"><Field label="Account" name="accountId"><select className={inputClass} defaultValue="" name="accountId" required><option disabled value="">Select account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></Field><Field label="As-of date" name="asOfDate"><input className={inputClass} defaultValue={defaultDate} name="asOfDate" required type="date" /></Field><Field errors={state.errors?.balances} label="Reported units" name="balances"><textarea className={textAreaClass} name="balances" placeholder="BTC: 0.25, ETH: 2, ADA: 500" required /></Field><Field label="Reported USD cash" name="reportedCashUsd"><input className={inputClass} defaultValue="0" name="reportedCashUsd" step="0.01" type="number" /></Field><Field label="Notes" name="notes"><textarea className={textAreaClass} name="notes" /></Field><FormFeedback message={state.message} tone={state.success ? "success" : "danger"} /><button className={buttonClass} disabled={pending || !accounts.length}>{pending ? "Saving..." : "Save reconciliation"}</button></form>;
}

export function ClassificationForm({ recordType, recordId, lines, currentLineId }: { recordType: string; recordId: number; lines: Option[]; currentLineId: number | null }) {
  const [state, action, pending] = useActionState(classifyRecord, initial);
  const [selectedLineId, setSelectedLineId] = useState(currentLineId?.toString() ?? "");
  return <form action={action} className="flex min-w-[300px] flex-wrap items-center justify-end gap-2"><input name="recordType" type="hidden" value={recordType} /><input name="recordId" type="hidden" value={recordId} /><select aria-label="Business line" className="h-9 min-w-0 flex-1 rounded-md border border-line-strong bg-surface px-2" name="businessLineId" onChange={(event) => setSelectedLineId(event.target.value)} required value={selectedLineId}><option disabled value="">Unclassified</option>{lines.map((line) => <option key={line.id} value={line.id}>{line.name}</option>)}</select><button className="h-9 rounded-md border border-line-strong px-3 font-semibold disabled:opacity-60" disabled={pending || !selectedLineId}>{pending ? "Saving..." : "Save"}</button>{state.message ? <span className={`basis-full text-right text-xs ${state.success ? "text-success" : "text-danger"}`}>{state.message}</span> : null}</form>;
}

export function BulkClassificationForm({ lines }: { lines: Option[] }) {
  const [state, action, pending] = useActionState(classifyAllUnclassified, initial);
  return <form action={action} className="flex flex-wrap items-end gap-3 rounded-lg border border-line bg-surface p-4 shadow-sm"><Field errors={state.errors?.businessLineId} label="Assign every unclassified record to" name="businessLineId"><select className={inputClass} defaultValue="" name="businessLineId" required><option disabled value="">Select business line</option>{lines.map((line) => <option key={line.id} value={line.id}>{line.name}</option>)}</select></Field><button className={buttonClass} disabled={pending || !lines.length}>{pending ? "Assigning..." : "Assign all unclassified"}</button><div className="basis-full"><FormFeedback message={state.message} tone={state.success ? "success" : "danger"} /></div></form>;
}

export function CapitalTransactionForm({ lines, bankAccounts, defaultDate }: { lines: Option[]; bankAccounts: Option[]; defaultDate: string }) {
  const [state, action, pending] = useActionState(addCapitalTransaction, initial);
  return <form action={action} className="grid gap-3 sm:grid-cols-2"><Field label="Date" name="transactionDate"><input className={inputClass} defaultValue={defaultDate} name="transactionDate" required type="date" /></Field><Field label="Activity" name="transactionType"><select className={inputClass} defaultValue="owner_contribution" name="transactionType"><option value="owner_contribution">Owner contribution</option><option value="owner_loan">Owner/related-party loan</option><option value="loan_repayment">Loan repayment</option><option value="owner_draw">Owner draw</option><option value="estimated_tax">Estimated tax payment</option></select></Field><Field label="Amount" name="amount"><input className={inputClass} min="0.01" name="amount" required step="0.01" type="number" /></Field><Field label="Bank account" name="bankAccountId"><select className={inputClass} defaultValue="" name="bankAccountId"><option value="">No bank attribution</option>{bankAccounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></Field><Field label="Business line" name="businessLineId"><select className={inputClass} defaultValue="" name="businessLineId"><option value="">Consolidated/shared</option>{lines.map((line) => <option key={line.id} value={line.id}>{line.name}</option>)}</select></Field><Field label="Counterparty" name="counterparty"><input className={inputClass} name="counterparty" /></Field><div className="sm:col-span-2"><Field label="Memo" name="memo"><textarea className={textAreaClass} name="memo" required /></Field></div><div className="sm:col-span-2"><FormFeedback message={state.message} tone={state.success ? "success" : "danger"} /></div><button className={buttonClass} disabled={pending}>{pending ? "Posting..." : "Record and post"}</button></form>;
}

type Identity = { legal_name: string; public_brand: string; tax_treatment: string; fictitious_name_status: string; fictitious_name_jurisdiction: string | null; notes: string | null } | null;
export function BusinessIdentityForm({ identity, fallbackLegalName, fallbackBrand }: { identity: Identity; fallbackLegalName: string; fallbackBrand: string }) {
  const [state, action, pending] = useActionState(updateBusinessIdentity, initial);
  return <form action={action} className="grid gap-3 sm:grid-cols-2"><Field label="Legal name" name="legalName"><input className={inputClass} defaultValue={identity?.legal_name ?? fallbackLegalName} name="legalName" required /></Field><Field label="Public brand" name="publicBrand"><input className={inputClass} defaultValue={identity?.public_brand ?? fallbackBrand} name="publicBrand" required /></Field><Field label="Tax treatment" name="taxTreatment"><select className={inputClass} defaultValue={identity?.tax_treatment ?? "single_member_disregarded"} name="taxTreatment"><option value="single_member_disregarded">Single-member disregarded entity</option><option value="s_corporation">S corporation</option><option value="c_corporation">C corporation</option><option value="partnership">Partnership</option><option value="other">Other</option></select></Field><Field label="Fictitious-name status" name="fictitiousNameStatus"><select className={inputClass} defaultValue={identity?.fictitious_name_status ?? "needs_review"} name="fictitiousNameStatus"><option value="needs_review">Needs review</option><option value="planned">Planned</option><option value="filed">Filed</option><option value="not_required">Not required</option></select></Field><Field label="Jurisdiction" name="fictitiousNameJurisdiction"><input className={inputClass} defaultValue={identity?.fictitious_name_jurisdiction ?? "Pennsylvania"} name="fictitiousNameJurisdiction" /></Field><div /><div className="sm:col-span-2"><Field label="Notes" name="notes"><textarea className={textAreaClass} defaultValue={identity?.notes ?? ""} name="notes" /></Field><FormFeedback message={state.message} tone={state.success ? "success" : "danger"} /></div><button className={buttonClass} disabled={pending}>{pending ? "Saving..." : "Save identity"}</button></form>;
}

export function CleanupItemForm({ lines, accounts, defaultDate }: { lines: Option[]; accounts: (Option & { code?: string })[]; defaultDate: string }) {
  const [state, action, pending] = useActionState(addCleanupItem, initial);
  const accountOptions = accounts.map((account) => <option key={account.id} value={account.id}>{account.code ? `${account.code} · ` : ""}{account.name}</option>);
  return <form action={action} className="grid gap-3 sm:grid-cols-2"><Field label="Type" name="itemType"><select className={inputClass} defaultValue="opening_balance" name="itemType"><option value="opening_balance">Historical opening balance</option><option value="owner_advance">Owner/related-party advance</option><option value="venmo_history">Venmo history</option><option value="uncategorized">Uncategorized history</option><option value="other">Other</option></select></Field><Field label="Effective date" name="effectiveDate"><input className={inputClass} defaultValue={defaultDate} name="effectiveDate" required type="date" /></Field><Field label="Amount" name="amount"><input className={inputClass} name="amount" step="0.01" type="number" /></Field><Field label="Business line" name="businessLineId"><select className={inputClass} defaultValue="" name="businessLineId"><option value="">Shared or unknown</option>{lines.map((line) => <option key={line.id} value={line.id}>{line.name}</option>)}</select></Field><Field label="Proposed debit" name="debitAccountId"><select className={inputClass} defaultValue="" name="debitAccountId"><option value="">Not determined</option>{accountOptions}</select></Field><Field label="Proposed credit" name="creditAccountId"><select className={inputClass} defaultValue="" name="creditAccountId"><option value="">Not determined</option>{accountOptions}</select></Field><div className="sm:col-span-2"><Field label="Description" name="description"><input className={inputClass} name="description" required /></Field></div><div className="sm:col-span-2"><Field label="Research / resolution notes" name="resolutionNotes"><textarea className={textAreaClass} name="resolutionNotes" /></Field><FormFeedback message={state.message} tone={state.success ? "success" : "danger"} /></div><button className={buttonClass} disabled={pending}>{pending ? "Adding..." : "Add cleanup item"}</button></form>;
}

export function PostCleanupItemForm({ itemId }: { itemId: number }) {
  const [state, action, pending] = useActionState(postHistoricalCleanupItem.bind(null, itemId), initial);
  return <form action={action}><button className="h-9 rounded-md border border-line-strong px-3 text-sm font-semibold disabled:opacity-60" disabled={pending}>{pending ? "Posting..." : "Post balance"}</button>{state.message ? <span className={state.success ? "ml-2 text-xs text-success" : "ml-2 text-xs text-danger"}>{state.message}</span> : null}</form>;
}
