import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDownToLine, ArrowUpDown, ArrowUpFromLine, BookOpenCheck, CalendarCheck, Coins, FilePlus2, History, Landmark, Scale, Settings2, Sparkles, Tags, Upload, UserRound } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { requireBusinessContext } from "@/lib/auth";
import { expensePaymentMethodLabel, expenseRequiresBankMatch } from "@/lib/domain/finance";
import { formatCurrency, formatDate } from "@/lib/format";
import { listBankAccounts, listBankStatementPeriods, listBankTransactions } from "@/lib/repositories/accounting-repository";
import { listExpensesAwaitingBankMatch } from "@/lib/repositories/expense-repository";
import { createClient } from "@/lib/supabase/server";
import { BankAccountForm } from "./finance-forms";

export const metadata: Metadata = { title: "Finance" };

export default async function FinancePage({ searchParams }: { searchParams: Promise<{ status?: string; sort?: string; direction?: string }> }) {
  const { status, sort: requestedSort, direction: requestedDirection } = await searchParams;
  const sort = requestedSort === "description" ? "description" : "date";
  const direction = requestedDirection === "asc" ? "asc" : "desc";
  const context = await requireBusinessContext();
  const { business } = context;
  const client = await createClient();
  const [accounts, transactions, statementPeriods, allUnmatchedExpenses] = await Promise.all([
    listBankAccounts(client, business.id),
    listBankTransactions(client, business.id, status, sort, direction),
    listBankStatementPeriods(client, business.id),
    listExpensesAwaitingBankMatch(client, business.id, sort, direction),
  ]);
  const allTransactions = status ? await listBankTransactions(client, business.id) : transactions;
  const unreviewed = allTransactions.filter((transaction) => transaction.status === "unreviewed");
  const reviewComplete = (expense: typeof allUnmatchedExpenses[number]) => expense.financial_classification_reviewed && (!expense.receipt_path || expense.receipt_review_status === "approved");
  const unreviewedCount = unreviewed.length + allUnmatchedExpenses.filter((expense) => !reviewComplete(expense)).length;
  const unmatchedExpenses = !status || status === "unreviewed" ? allUnmatchedExpenses.filter((expense) => expenseRequiresBankMatch(expense.payment_method)) : [];
  const nonBankFundedExpenses = !status ? allUnmatchedExpenses.filter((expense) => !expenseRequiresBankMatch(expense.payment_method)) : [];
  const deposits = allTransactions.filter((transaction) => transaction.amount > 0).reduce((sum, transaction) => sum + transaction.amount, 0);
  const withdrawals = allTransactions.filter((transaction) => transaction.amount < 0).reduce((sum, transaction) => sum + Math.abs(transaction.amount), 0);
  const sortHref = (column: "date" | "description") => {
    const nextDirection = sort === column ? (direction === "asc" ? "desc" : "asc") : (column === "date" ? "desc" : "asc");
    const params = new URLSearchParams({ sort: column, direction: nextDirection });
    if (status) params.set("status", status);
    return `/finance?${params}`;
  };
  const filterHref = (value: string) => {
    const params = new URLSearchParams({ sort, direction });
    if (value) params.set("status", value);
    return `/finance?${params}`;
  };
  const actions = <div className="flex flex-wrap gap-2">{context.role !== "employee" ? <><Link className="flex h-11 items-center gap-2 rounded-md border border-line-strong px-4 font-semibold" href="/reports/books"><BookOpenCheck size={17} />Books</Link><Link className="flex h-11 items-center gap-2 rounded-md border border-line-strong px-4 font-semibold" href="/finance/digital-assets"><Coins size={17} />Crypto</Link><Link className="flex h-11 items-center gap-2 rounded-md border border-line-strong px-4 font-semibold" href="/finance/classification"><Tags size={17} />Lines</Link><Link className="flex h-11 items-center gap-2 rounded-md border border-line-strong px-4 font-semibold" href="/finance/capital"><UserRound size={17} />Owner</Link><Link className="flex h-11 items-center gap-2 rounded-md border border-line-strong px-4 font-semibold" href="/finance/cleanup"><History size={17} />Cleanup</Link><Link className="flex h-11 items-center gap-2 rounded-md border border-line-strong px-4 font-semibold" href="/finance/business-settings"><Settings2 size={17} />Identity</Link><Link className="flex h-11 items-center gap-2 rounded-md border border-line-strong px-4 font-semibold" href="/finance/adjustments/new"><Scale size={17} />Adjustments</Link><Link className="flex h-11 items-center gap-2 rounded-md border border-line-strong px-4 font-semibold" href="/finance/month-end"><CalendarCheck size={17} />Month-end</Link></> : null}<Link className="flex h-11 items-center gap-2 rounded-md bg-brand px-4 font-semibold text-on-brand" href="/finance/import"><Upload size={17} />Import statement</Link></div>;
  return <div className="mx-auto w-full max-w-[1400px] px-4 py-6 sm:px-6 lg:px-8">
    <PageHeader actions={actions} description="Reconcile actual cash activity with expenses and customer payments." title="Finance" />
    {context.role !== "employee" ? <div className="flex flex-wrap gap-2 pt-6"><Link className="inline-flex h-11 items-center gap-2 rounded-md bg-brand px-4 font-semibold text-on-brand" href="/finance/matching"><Sparkles size={17} />Review automatic expense matches</Link><Link className="inline-flex h-11 items-center gap-2 rounded-md border border-line-strong px-4 font-semibold" href="/finance/suggestions"><Sparkles size={17} />Approve learned classifications</Link></div> : null}
    <section className="grid grid-cols-2 gap-3 py-6 sm:grid-cols-4">
      {[["Unreviewed items", String(unreviewedCount)], ["Imported deposits", formatCurrency(deposits)], ["Imported withdrawals", formatCurrency(withdrawals)], ["Net imported cash", formatCurrency(deposits - withdrawals)]].map(([label, value]) => <div className="rounded-lg border border-line bg-surface p-4 shadow-sm" key={label}><p className="text-xl font-bold tabular-nums">{value}</p><p className="mt-1 text-xs text-muted">{label}</p></div>)}
    </section>
    {nonBankFundedExpenses.length ? <section className="mb-5 overflow-hidden rounded-lg border border-line bg-surface shadow-sm"><div className="border-b border-line px-4 py-3"><h2 className="font-bold">Expenses with no statement match required</h2><p className="mt-1 text-sm text-muted">These were paid with personal funds or business cash, so they do not require importing a personal bank statement.</p></div><div className="divide-y divide-line">{nonBankFundedExpenses.map((expense) => { const reviewed = reviewComplete(expense); return <div className="grid gap-3 px-4 py-4 sm:grid-cols-[130px_minmax(0,1fr)_minmax(220px,0.8fr)_120px_150px] sm:items-center" key={expense.id}><span>{formatDate(expense.expense_date)}</span><div className="min-w-0"><p className="truncate font-semibold">{expense.vendor || expense.description || `Expense #${expense.id}`}</p><p className="truncate text-xs text-muted">{expensePaymentMethodLabel(expense.payment_method)}</p></div><StatusBadge label={reviewed ? "reviewed · no bank match" : "unreviewed · no bank match"} status={reviewed ? "matched" : "unreviewed"} /><strong className="text-right">{expense.transaction_type === "refund" ? "+" : "-"}{formatCurrency(Math.abs(expense.amount))}</strong><Link className={`inline-flex h-9 items-center justify-center rounded-md px-3 font-semibold ${reviewed ? "border border-line-strong" : "bg-brand text-on-brand"}`} href={`/expenses/${expense.id}`}>{reviewed ? "View expense" : "Review expense"}</Link></div>; })}</div></section> : null}
    {unmatchedExpenses.length ? <section className="mb-5 overflow-hidden rounded-lg border border-line bg-surface shadow-sm"><div className="border-b border-line px-4 py-3"><h2 className="font-bold">Recorded expenses awaiting bank match</h2><p className="mt-1 text-sm text-muted">Review confirms the expense details. A bank match is a separate step completed when its statement transaction is available.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] table-fixed text-left text-sm"><colgroup><col className="w-[130px]" /><col /><col className="w-[145px]" /><col className="w-[120px]" /><col className="w-[160px]" /></colgroup><thead className="bg-surface-muted text-xs uppercase text-muted"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Expense</th><th className="px-4 py-3">Review status</th><th className="px-4 py-3 text-right">Amount</th><th className="px-4 py-3">Action</th></tr></thead><tbody className="divide-y divide-line">{unmatchedExpenses.map((expense) => { const reviewed = expense.financial_classification_reviewed && (!expense.receipt_path || expense.receipt_review_status === "approved"); return <tr key={expense.id}><td className="whitespace-nowrap px-4 py-3">{formatDate(expense.expense_date)}</td><td className="truncate px-4 py-3 font-semibold" title={expense.vendor || expense.description || `Expense #${expense.id}`}>{expense.vendor || expense.description || `Expense #${expense.id}`}</td><td className="px-4 py-3"><StatusBadge label={reviewed ? "reviewed" : "unreviewed"} status={reviewed ? "matched" : "unreviewed"} /></td><td className="whitespace-nowrap px-4 py-3 text-right font-bold tabular-nums">{expense.transaction_type === "refund" ? "+" : "-"}{formatCurrency(Math.abs(expense.amount))}</td><td className="px-4 py-3"><Link className={`inline-flex h-9 items-center rounded-md px-3 font-semibold ${reviewed ? "border border-line-strong" : "bg-brand text-on-brand"}`} href={`/expenses/${expense.id}`}>{reviewed ? "View expense" : "Review expense"}</Link></td></tr>; })}</tbody></table></div></section> : null}
    <div className="grid gap-5 2xl:grid-cols-[minmax(0,1fr)_320px]">
      <section className="min-w-0 overflow-hidden rounded-lg border border-line bg-surface shadow-sm">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-line px-4 py-3"><h2 className="font-bold">Bank transactions</h2><div className="flex flex-wrap gap-2 text-sm">{["", "unreviewed", "partially_matched", "matched", "excluded"].map((value) => <Link className={`rounded-md px-2 py-1 font-semibold ${status === value || (!status && !value) ? "bg-brand text-on-brand" : "border border-line-strong"}`} href={filterHref(value)} key={value}>{value ? value.replaceAll("_", " ") : "All"}</Link>)}</div></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[860px] table-fixed text-left text-sm"><colgroup><col className="w-[130px]" /><col className="w-[190px]" /><col /><col className="w-[145px]" /><col className="w-[120px]" /><col className="w-[190px]" /></colgroup><thead className="bg-surface-muted text-xs uppercase text-muted"><tr><th className="px-4 py-3"><Link className="inline-flex items-center gap-1 hover:text-foreground" href={sortHref("date")}>Date<ArrowUpDown size={13} /></Link></th><th className="px-4 py-3">Account</th><th className="px-4 py-3"><Link className="inline-flex items-center gap-1 hover:text-foreground" href={sortHref("description")}>Description<ArrowUpDown size={13} /></Link></th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Amount</th><th className="px-4 py-3">Action</th></tr></thead><tbody className="divide-y divide-line">{transactions.map((transaction) => <tr key={transaction.id}><td className="whitespace-nowrap px-4 py-3">{formatDate(transaction.transaction_date)}</td><td className="break-words px-4 py-3">{transaction.bank_accounts?.name ?? `Account #${transaction.account_id}`}</td><td className="truncate px-4 py-3 font-semibold" title={transaction.description}>{transaction.description}</td><td className="px-4 py-3"><StatusBadge label={transaction.status.replaceAll("_", " ")} status={transaction.status} /></td><td className={`whitespace-nowrap px-4 py-3 text-right font-bold tabular-nums ${transaction.amount > 0 ? "text-success" : ""}`}>{transaction.amount > 0 ? "+" : "-"}{formatCurrency(Math.abs(transaction.amount))}</td><td className="px-4 py-3">{["unreviewed", "partially_matched"].includes(transaction.status) ? <div className="flex items-center gap-2"><Link className="inline-flex h-9 whitespace-nowrap rounded-md bg-brand px-3 font-semibold text-on-brand" href={`/finance/transactions/${transaction.id}`}>Review / match</Link>{transaction.status === "unreviewed" ? <>{transaction.amount < 0 ? <Link aria-label="Create expense" className="inline-flex size-9 shrink-0 items-center justify-center rounded-md border border-line-strong" href={`/expenses/new?bankTransaction=${transaction.id}`}><ArrowUpFromLine size={15} /></Link> : <Link aria-label="Record payment" className="inline-flex size-9 shrink-0 items-center justify-center rounded-md border border-line-strong" href={`/finance/payments/new?bankTransaction=${transaction.id}`}><ArrowDownToLine size={15} /></Link>}</> : null}</div> : transaction.status === "matched" ? "Matched" : transaction.excluded_reason || "Excluded"}</td></tr>)}{!transactions.length && <tr><td className="px-5 py-14 text-center text-muted" colSpan={6}>No imported bank transactions.</td></tr>}</tbody></table></div>
      </section>
      <div className="min-w-0 space-y-5"><section className="rounded-lg border border-line bg-surface p-5 shadow-sm"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><Landmark className="text-brand" size={18} /><h2 className="font-bold">Accounts</h2></div>{context.role !== "employee" ? <Link aria-label="New reconciliation" className="flex size-9 items-center justify-center rounded-md border border-line-strong" href="/finance/reconciliations/new"><FilePlus2 size={16} /></Link> : null}</div><div className="mt-4 space-y-3">{accounts.map((account) => <div className="border-b border-line pb-3 text-sm" key={account.id}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="break-words font-semibold">{account.name}</p><p className="break-words text-muted">{account.institution || account.account_type.replaceAll("_", " ")}{account.last_four ? ` · ${account.last_four}` : ""}</p></div>{context.role !== "employee" && account.account_type !== "cash" ? <Link className="shrink-0 font-semibold text-brand" href={`/finance/reconciliations/new?account=${account.id}`}>Reconcile</Link> : null}</div></div>)}{!accounts.length && <p className="text-sm text-muted">Add the account used by your statement export.</p>}</div></section><section className="rounded-lg border border-line bg-surface p-5 shadow-sm"><h2 className="font-bold">Add account</h2><div className="mt-4"><BankAccountForm /></div></section></div>
    </div>
    {context.role !== "employee" ? <section className="mt-5 overflow-hidden rounded-lg border border-line bg-surface shadow-sm"><div className="flex items-center justify-between gap-3 border-b border-line px-5 py-4"><div><h2 className="font-bold">Statement reconciliations</h2><p className="mt-1 text-sm text-muted">A reconciled statement agrees with both its imported rows and posted book activity.</p></div><Link className="font-semibold text-brand" href="/finance/reconciliations/new">New</Link></div><div className="divide-y divide-line">{statementPeriods.slice(0, 12).map((period) => <Link className="grid gap-2 px-5 py-4 hover:bg-surface-muted sm:grid-cols-[1fr_auto_auto] sm:items-center" href={`/finance/reconciliations/${period.id}`} key={period.id}><div><p className="font-semibold">{period.bank_accounts?.name}</p><p className="text-sm text-muted">{formatDate(period.statement_start_date)} – {formatDate(period.statement_end_date)}</p></div><StatusBadge label={period.status} status={period.status} /><strong className="text-right">{formatCurrency(period.closing_balance)}</strong></Link>)}{!statementPeriods.length ? <p className="px-5 py-8 text-sm text-muted">Import a complete statement, then create its reconciliation period.</p> : null}</div></section> : null}
  </div>;
}
