"use client";

import { useActionState } from "react";
import { Upload } from "lucide-react";
import { FormFeedback } from "@/components/form-feedback";
import { inputClass } from "@/components/form-fields";
import { formatCurrency, formatDate } from "@/lib/format";
import { confirmBankImport, previewBankImport, type BankImportState } from "../actions";

function ConfirmImport({ state }: { state: BankImportState }) {
  const [result, action, pending] = useActionState(confirmBankImport, {} as BankImportState);
  return <div className="space-y-3"><form action={action}><input name="accountId" type="hidden" value={state.accountId} /><input name="fileName" type="hidden" value={state.fileName} /><input name="sourceSha256" type="hidden" value={state.sourceSha256} /><input name="rows" type="hidden" value={JSON.stringify(state.rows)} /><button className="h-11 rounded-md bg-brand px-4 font-semibold text-on-brand disabled:opacity-60" disabled={pending || Boolean(state.errors?.length)}>{pending ? "Importing..." : `Import ${state.rows?.length ?? 0} transactions`}</button></form><FormFeedback message={result.message} tone={result.result ? "success" : "danger"} />{result.result ? <p className="text-sm text-muted">Created {result.result.created}; skipped {result.result.skipped} duplicate transactions.</p> : null}</div>;
}

export function BankImportWorkflow({ accounts }: { accounts: { id: number; name: string }[] }) {
  const [state, action, pending] = useActionState(previewBankImport, {} as BankImportState);
  return <div className="mt-6 space-y-6"><form action={action} className="rounded-lg border border-line bg-surface p-5 shadow-sm"><div className="grid gap-4 sm:grid-cols-2"><label className="font-semibold">Account<select className={`${inputClass} mt-2`} name="accountId" required><option value="">Select account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label className="font-semibold">Statement<input accept=".xlsx,.csv" className={`${inputClass} mt-2 p-2`} name="statement" required type="file" /></label></div><p className="mt-3 text-sm text-muted">Bank, credit-card, and Venmo CSV statements are supported. Venmo processing fees become separate expense rows so the imported activity matches the Venmo balance.</p><button className="mt-4 flex h-11 items-center gap-2 rounded-md bg-brand px-4 font-semibold text-on-brand disabled:opacity-60" disabled={pending || !accounts.length}><Upload size={17} />{pending ? "Reading..." : "Preview statement"}</button></form>{state.errors?.length ? <div className="rounded-md border border-danger-line bg-danger-soft p-4 text-danger-strong"><p className="font-semibold">Review these issues</p><ul className="mt-2 list-disc pl-5 text-sm">{state.errors.map((error) => <li key={error}>{error}</li>)}</ul></div> : null}{state.rows ? <section><h2 className="mb-3 font-bold">Preview: {state.rows.length} transactions</h2><div className="max-h-[520px] overflow-auto rounded-lg border border-line bg-surface"><table className="w-full min-w-[760px] text-left text-sm"><thead className="sticky top-0 bg-surface-muted text-xs uppercase text-muted"><tr><th className="px-3 py-3">Row</th><th className="px-3 py-3">Date</th><th className="px-3 py-3">Description</th><th className="px-3 py-3 text-right">Amount</th></tr></thead><tbody className="divide-y divide-line">{state.rows.map((row) => <tr key={row.fingerprint}><td className="px-3 py-3">{row.rowNumber}</td><td className="px-3 py-3">{formatDate(row.transactionDate)}</td><td className="px-3 py-3 font-semibold">{row.description}</td><td className="px-3 py-3 text-right">{row.amount > 0 ? "+" : "-"}{formatCurrency(Math.abs(row.amount))}</td></tr>)}</tbody></table></div><div className="mt-4"><ConfirmImport state={state} /></div></section> : null}</div>;
}
