"use client";

import { useActionState } from "react";
import { Archive, RotateCcw, Trash2 } from "lucide-react";
import { FormFeedback } from "@/components/form-feedback";
import { changeRecordLifecycle, type RecordLifecycleState, type RemovableRecordType } from "@/app/(app)/record-lifecycle-actions";

export function RecordLifecycleControl({ archived, id, label, type }: { archived: boolean; id: number; label: string; type: RemovableRecordType }) {
  const boundAction = changeRecordLifecycle.bind(null, type, id);
  const [state, action, pending] = useActionState(boundAction, {} as RecordLifecycleState);
  const accountingWarning = type === "invoice" || type === "expense" || type === "job";
  return <div className="space-y-3">
    {archived
      ? <><p className="text-sm text-muted">This {label} is archived and excluded from normal lists.</p><form action={action}><button className="flex h-10 items-center gap-2 rounded-md border border-line-strong px-4 font-semibold disabled:opacity-60" disabled={pending} name="intent" value="restore"><RotateCcw size={16} />{pending ? "Restoring..." : "Restore"}</button></form></>
      : <details className="rounded-md border border-line p-3"><summary className="cursor-pointer font-semibold text-danger">Remove {label}…</summary><form action={action} className="mt-4 space-y-3"><label className="block text-sm font-semibold">Reason<textarea className="mt-1 min-h-20 w-full rounded-md border border-line-strong bg-surface p-3 font-normal" name="reason" required /></label><label className="flex items-start gap-2 text-sm"><input className="mt-1" name="confirm" required type="checkbox" value="yes" /><span>I understand this removes the record from normal lists.</span></label><div className="flex flex-wrap gap-2"><button className="flex h-10 items-center gap-2 rounded-md border border-danger px-4 font-semibold text-danger disabled:opacity-60" disabled={pending} name="intent" value="archive"><Archive size={16} />{pending ? "Working..." : "Archive"}</button><button className="flex h-10 items-center gap-2 rounded-md bg-danger px-4 font-semibold text-white disabled:opacity-60" disabled={pending} name="intent" value="delete"><Trash2 size={16} />Permanently delete if safe</button></div><p className="text-xs leading-5 text-muted">Permanent deletion is blocked when linked accounting or operational records exist.</p></form></details>}
    <details className="rounded-md border border-danger/40 bg-danger/5 p-3"><summary className="cursor-pointer font-semibold text-danger">Override safety checks…</summary><form action={action} className="mt-4 space-y-3"><p className="text-sm leading-6 text-danger">This permanently deletes the {label} and its dependent records. {accountingWarning ? "Linked payments, expenses, ledger entries, or labor may also be deleted, and matched bank transactions will return to unreviewed." : "A converted job is kept but detached from this quote."} This cannot be undone.</p><label className="block text-sm font-semibold">Why are you overriding the safety check?<textarea className="mt-1 min-h-20 w-full rounded-md border border-danger bg-surface p-3 font-normal" name="reason" required /></label><label className="flex items-start gap-2 text-sm"><input className="mt-1" name="confirm" required type="checkbox" value="yes" /><span>I understand the selected record and its dependent data will be permanently deleted.</span></label><label className="block text-sm font-semibold">Type DELETE to confirm<input autoComplete="off" className="mt-1 h-11 w-full rounded-md border border-danger bg-surface px-3 font-normal" name="overrideConfirmation" pattern="DELETE" required /></label><button className="flex h-10 items-center gap-2 rounded-md bg-danger px-4 font-semibold text-white disabled:opacity-60" disabled={pending} name="intent" value="force_delete"><Trash2 size={16} />{pending ? "Deleting..." : "Override and permanently delete"}</button></form></details>
    <FormFeedback message={state.message} tone={state.success ? "success" : "danger"} />
  </div>;
}
