"use server";
import { createHash } from "node:crypto";
import { revalidatePath } from "next/cache";
import { readSheet } from "read-excel-file/node";
import { requireBusinessContext } from "@/lib/auth";
import { normalizeImportRows, type JobImportRow } from "@/lib/domain/imports";
import { importJobRows } from "@/lib/repositories/import-repository";
import { createClient } from "@/lib/supabase/server";
export type ImportState = { message?: string; errors?: string[]; rows?: JobImportRow[]; fileName?: string; sourceSha256?: string; result?: { already_imported: boolean; customers_created: number; customers_updated: number; jobs_created: number; duplicates_skipped: number } };
function csvRows(text: string) { const rows: string[][] = []; let row: string[] = []; let value = ""; let quoted = false; for (let index = 0; index < text.length; index += 1) { const char = text[index]; if (char === '"' && quoted && text[index + 1] === '"') { value += '"'; index += 1; } else if (char === '"') quoted = !quoted; else if (char === "," && !quoted) { row.push(value); value = ""; } else if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && text[index + 1] === "\n") index += 1; row.push(value); if (row.some(Boolean)) rows.push(row); row = []; value = ""; } else value += char; } row.push(value); if (row.some(Boolean)) rows.push(row); return rows; }
export async function previewImport(_: ImportState, formData: FormData): Promise<ImportState> { await requireBusinessContext(); const file = formData.get("spreadsheet"); if (!(file instanceof File) || !file.size) return { errors: ["Choose a spreadsheet to import."] }; if (file.size > 5_000_000) return { errors: ["The spreadsheet must be smaller than 5 MB."] }; const extension = file.name.toLowerCase().split(".").pop(); if (!extension || !["xlsx", "csv"].includes(extension)) return { errors: ["Use an .xlsx or .csv spreadsheet."] }; try { const buffer = Buffer.from(await file.arrayBuffer()); const raw = extension === "csv" ? csvRows(buffer.toString("utf8")) : await readSheet(buffer, "Jobs"); const preview = normalizeImportRows(raw as unknown[][]); return { ...preview, fileName: file.name, sourceSha256: createHash("sha256").update(buffer).digest("hex") }; } catch { return { errors: ["The spreadsheet could not be read. Confirm that it contains a Jobs worksheet."] }; } }
export async function confirmImport(_: ImportState, formData: FormData): Promise<ImportState> { const { business } = await requireBusinessContext(); try { const rows = JSON.parse(String(formData.get("rows") || "[]")) as JobImportRow[]; const fileName = String(formData.get("fileName") || ""); const sourceSha256 = String(formData.get("sourceSha256") || ""); if (!Array.isArray(rows) || !rows.length || !fileName || !/^[0-9a-f]{64}$/.test(sourceSha256)) return { message: "The import preview expired. Choose the file again." }; const result = await importJobRows(await createClient(), business.id, fileName, sourceSha256, rows); revalidatePath("/customers"); revalidatePath("/jobs"); revalidatePath("/dashboard"); revalidatePath("/imports/jobs"); return { result, message: result.already_imported ? "This exact spreadsheet was already imported." : "Spreadsheet import complete." }; } catch (error) { return { message: error instanceof Error ? error.message : "The jobs could not be imported." }; } }
