"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireBusinessContext } from "@/lib/auth";
import { addMaintenance, createEquipment } from "@/lib/repositories/equipment-repository";
import { createClient } from "@/lib/supabase/server";
import { equipmentFormSchema, formValues, maintenanceFormSchema } from "@/lib/validation/business-records";
export type EquipmentState = { message?: string; errors?: Record<string, string[]> };
export async function saveEquipment(_: EquipmentState, formData: FormData): Promise<EquipmentState> { const parsed = equipmentFormSchema.safeParse({ ...formValues(formData, ["name", "equipmentType", "makeModel", "serialNumber", "hourMeter", "notes"]), active: formData.get("active") === "on" }); if (!parsed.success) return { errors: parsed.error.flatten().fieldErrors }; const { business } = await requireBusinessContext(); try { await createEquipment(await createClient(), { business_id: business.id, name: parsed.data.name, equipment_type: parsed.data.equipmentType ?? null, make_model: parsed.data.makeModel ?? null, serial_number: parsed.data.serialNumber ?? null, hour_meter: parsed.data.hourMeter ?? null, active: parsed.data.active, notes: parsed.data.notes ?? null }); revalidatePath("/equipment"); redirect("/equipment"); } catch (error) { if (error && typeof error === "object" && "digest" in error) throw error; return { message: "The equipment could not be saved." }; } }
export async function saveMaintenance(_: EquipmentState, formData: FormData): Promise<EquipmentState> { const parsed = maintenanceFormSchema.safeParse(formValues(formData, ["equipmentId", "serviceDate", "serviceType", "hourMeter", "cost", "nextDueDate", "nextDueHours", "notes"])); if (!parsed.success) return { errors: parsed.error.flatten().fieldErrors }; if (!parsed.data.equipmentId || !parsed.data.serviceDate) return { message: "Equipment and service date are required." }; const { business } = await requireBusinessContext(); try { await addMaintenance(await createClient(), { businessId: business.id, ...parsed.data, equipmentId: parsed.data.equipmentId, serviceDate: parsed.data.serviceDate }); revalidatePath("/equipment"); revalidatePath("/dashboard"); redirect("/equipment"); } catch (error) { if (error && typeof error === "object" && "digest" in error) throw error; return { message: "The maintenance record could not be saved." }; } }
