"use client";
import Link from "next/link";
import { Save } from "lucide-react";
import { useActionState } from "react";
import { Field, inputClass, textAreaClass } from "@/components/form-fields";
import { FormFeedback } from "@/components/form-feedback";
import { saveEquipment, saveMaintenance, type EquipmentState } from "./actions";
const Submit = ({ pending, label }: { pending: boolean; label: string }) => <button className="flex h-11 items-center gap-2 rounded-md bg-brand px-4 font-semibold text-on-brand disabled:opacity-60" disabled={pending}><Save size={17} />{pending ? "Saving..." : label}</button>;
export function EquipmentForm() { const [state, action, pending] = useActionState(saveEquipment, {} as EquipmentState); return <form action={action} className="mt-6 space-y-6"><div className="grid gap-5 sm:grid-cols-2"><Field errors={state.errors?.name} label="Equipment name" name="name"><input className={inputClass} id="name" name="name" required /></Field><Field errors={state.errors?.equipmentType} label="Type" name="equipmentType"><input className={inputClass} id="equipmentType" name="equipmentType" /></Field><Field errors={state.errors?.makeModel} label="Make / model" name="makeModel"><input className={inputClass} id="makeModel" name="makeModel" /></Field><Field errors={state.errors?.serialNumber} label="Serial number" name="serialNumber"><input className={inputClass} id="serialNumber" name="serialNumber" /></Field><Field errors={state.errors?.hourMeter} label="Hour meter" name="hourMeter"><input className={inputClass} id="hourMeter" min="0" name="hourMeter" step="0.1" type="number" /></Field><label className="flex items-center gap-3 self-end pb-3 font-semibold"><input className="size-5 accent-brand" defaultChecked name="active" type="checkbox" />Active</label><div className="sm:col-span-2"><Field errors={state.errors?.notes} label="Notes" name="notes"><textarea className={textAreaClass} id="notes" name="notes" /></Field></div></div><FormFeedback message={state.message} /><div className="flex gap-3"><Submit label="Save equipment" pending={pending} /><Link className="flex h-11 items-center rounded-md border border-line-strong px-4 font-semibold" href="/equipment">Cancel</Link></div></form>; }
export function MaintenanceForm({ equipment, today, selectedId }: { equipment: { id: number; name: string }[]; today: string; selectedId?: number }) { const [state, action, pending] = useActionState(saveMaintenance, {} as EquipmentState); return <form action={action} className="mt-6 space-y-6"><div className="grid gap-5 sm:grid-cols-2"><Field errors={state.errors?.equipmentId} label="Equipment" name="equipmentId"><select className={inputClass} defaultValue={selectedId ?? ""} id="equipmentId" name="equipmentId" required><option value="">Select equipment</option>{equipment.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field errors={state.errors?.serviceDate} label="Service date" name="serviceDate"><input className={inputClass} defaultValue={today} id="serviceDate" name="serviceDate" required type="date" /></Field><Field errors={state.errors?.serviceType} label="Service type" name="serviceType"><input className={inputClass} id="serviceType" name="serviceType" required /></Field><Field errors={state.errors?.hourMeter} label="Hour meter" name="hourMeter"><input className={inputClass} id="hourMeter" min="0" name="hourMeter" step="0.1" type="number" /></Field><Field errors={state.errors?.cost} label="Cost" name="cost"><input className={inputClass} id="cost" min="0" name="cost" step="0.01" type="number" /></Field><Field errors={state.errors?.nextDueDate} label="Next due date" name="nextDueDate"><input className={inputClass} id="nextDueDate" name="nextDueDate" type="date" /></Field><Field errors={state.errors?.nextDueHours} label="Next due hours" name="nextDueHours"><input className={inputClass} id="nextDueHours" min="0" name="nextDueHours" step="0.1" type="number" /></Field><div className="sm:col-span-2"><Field errors={state.errors?.notes} label="Notes" name="notes"><textarea className={textAreaClass} id="notes" name="notes" /></Field></div></div><FormFeedback message={state.message} /><div className="flex gap-3"><Submit label="Save maintenance" pending={pending} /><Link className="flex h-11 items-center rounded-md border border-line-strong px-4 font-semibold" href="/equipment">Cancel</Link></div></form>; }
