-- Distinct from internal_notes: this is included in the AI estimate request,
-- whereas internal_notes and hazard_notes stay out of the AI data boundary.
alter table public.quotes add column special_instructions text;

create table public.quote_knowledge (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  title text not null check (char_length(trim(title)) between 1 and 200),
  body text not null check (char_length(trim(body)) between 1 and 5000),
  tags text[] not null default '{}'::text[],
  source_quote_id bigint references public.quotes(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quote_knowledge_business_id_key unique (business_id, id)
);

create index quote_knowledge_business_created_idx
  on public.quote_knowledge (business_id, created_at desc, id desc);
create index quote_knowledge_source_quote_idx
  on public.quote_knowledge (source_quote_id)
  where source_quote_id is not null;
create index quote_knowledge_created_by_idx
  on public.quote_knowledge (created_by)
  where created_by is not null;
create index quote_knowledge_updated_by_idx
  on public.quote_knowledge (updated_by)
  where updated_by is not null;

create trigger quote_knowledge_set_updated_at
before update on public.quote_knowledge
for each row execute function private.set_updated_at();

alter table public.quote_knowledge enable row level security;

create policy quote_knowledge_select_business_member
on public.quote_knowledge for select to authenticated
using ((select private.is_business_member(business_id)));
create policy quote_knowledge_insert_business_member
on public.quote_knowledge for insert to authenticated
with check ((select private.is_business_member(business_id)) and created_by = (select auth.uid()));
create policy quote_knowledge_update_business_member
on public.quote_knowledge for update to authenticated
using ((select private.is_business_member(business_id)))
with check ((select private.is_business_member(business_id)) and updated_by = (select auth.uid()));
create policy quote_knowledge_delete_business_member
on public.quote_knowledge for delete to authenticated
using ((select private.is_business_member(business_id)));

grant select, insert, update, delete on public.quote_knowledge to authenticated;
grant usage, select on sequence public.quote_knowledge_id_seq to authenticated;
